apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mongodb-10.6.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 1m0s
  releaseName: mongodb-10.6.5
